namespace Ff7.Accessibility.Reloaded;

/// <summary>
/// Native, reusable Shinra Headquarters elevator targets.
/// Story navigation still describes the mandatory infiltration sequence; these
/// definitions keep every usable elevator door and cabin control available in
/// the Objects category for ordinary travel between floors.
/// </summary>
public static class ShinraElevatorObjectCatalog
{
    private static readonly IReadOnlyList<FieldNavigationObjectDefinition> Definitions =
    [
        new(
            232,
            16,
            FieldNavigationObjectKind.Named,
            Label: "Lobby elevator control switch; press OK",
            SourceFieldName: "blinele",
            SourceEntityName: "SWITCH",
            TargetKind: FieldNavigationObjectTargetKind.Location,
            StaticX: -105,
            StaticY: 110,
            StaticZ: 0),
        new(
            233,
            7,
            FieldNavigationObjectKind.Named,
            Label: "Passenger elevator floor-selection panel; press OK",
            SourceFieldName: "eleout",
            SourceEntityName: "lin0",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -2,
            StaticY: 37,
            StaticZ: -1),
        new(
            233,
            8,
            FieldNavigationObjectKind.Named,
            Label: "Passenger elevator exit to selected floor",
            SourceFieldName: "eleout",
            SourceEntityName: "jp",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: 67,
            StaticY: -151,
            StaticZ: -1),
        new(
            234,
            15,
            FieldNavigationObjectKind.Named,
            Label: "Left lobby elevator to floor 59",
            SourceFieldName: "blin1",
            SourceEntityName: "ELINEL",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -1558,
            StaticY: -117,
            StaticZ: 0),
        new(
            234,
            16,
            FieldNavigationObjectKind.Named,
            Label: "Right lobby elevator to floor 59",
            SourceFieldName: "blin1",
            SourceEntityName: "ELINER",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -1550,
            StaticY: 138,
            StaticZ: 0),
        new(
            235,
            18,
            FieldNavigationObjectKind.Named,
            Label: "Left lobby elevator to floor 59",
            SourceFieldName: "blin2",
            SourceEntityName: "ELINEL",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -1558,
            StaticY: -117,
            StaticZ: 0),
        new(
            235,
            19,
            FieldNavigationObjectKind.Named,
            Label: "Right lobby elevator to floor 59",
            SourceFieldName: "blin2",
            SourceEntityName: "ELINER",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -1550,
            StaticY: 138,
            StaticZ: 0),
        new(
            237,
            12,
            FieldNavigationObjectKind.Named,
            Label: "Left lobby elevator to floor 59",
            SourceFieldName: "blin3_1",
            SourceEntityName: "ELINEL",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -1558,
            StaticY: -117,
            StaticZ: 0),
        new(
            237,
            13,
            FieldNavigationObjectKind.Named,
            Label: "Right lobby elevator to floor 59",
            SourceFieldName: "blin3_1",
            SourceEntityName: "ELINER",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -1550,
            StaticY: 138,
            StaticZ: 0),
        new(
            238,
            14,
            FieldNavigationObjectKind.Named,
            Label: "Floor 59 lower elevator, left door",
            SourceFieldName: "blin59",
            SourceEntityName: "LINEUL",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -691,
            StaticY: 1337,
            StaticZ: 1),
        new(
            238,
            15,
            FieldNavigationObjectKind.Named,
            Label: "Floor 59 lower elevator, right door",
            SourceFieldName: "blin59",
            SourceEntityName: "LINEUR",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: -461,
            StaticY: 1335,
            StaticZ: 0),
        new(
            238,
            16,
            FieldNavigationObjectKind.Named,
            Label: "Floor 59 upper-floor elevator, right door",
            SourceFieldName: "blin59",
            SourceEntityName: "DLINER",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: 605,
            StaticY: -643,
            StaticZ: -1),
        new(
            238,
            17,
            FieldNavigationObjectKind.Named,
            Label: "Floor 59 upper-floor elevator, left door",
            SourceFieldName: "blin59",
            SourceEntityName: "DLINEL",
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: 603,
            StaticY: -366,
            StaticZ: 0),
        CreatePassengerDoor(239, 12, "Floor 60 passenger elevator, left door", "blin60_1", "ELINEL", -130, -937),
        CreatePassengerDoor(239, 13, "Floor 60 passenger elevator, right door", "blin60_1", "ELINER", 131, -937),
        CreatePassengerDoor(241, 18, "Floor 61 passenger elevator, left door", "blin61", "ELINEL", -130, -994),
        CreatePassengerDoor(241, 19, "Floor 61 passenger elevator, right door", "blin61", "ELINER", 131, -994),
        CreatePassengerDoor(242, 13, "Floor 62 passenger elevator, left door", "blin62_1", "ELINEL", -130, -994),
        CreatePassengerDoor(242, 14, "Floor 62 passenger elevator, right door", "blin62_1", "ELINER", 131, -994),
        CreatePassengerDoor(245, 9, "Floor 63 passenger elevator, left door", "blin63_1", "ELINEL", -130, -994),
        CreatePassengerDoor(245, 10, "Floor 63 passenger elevator, right door", "blin63_1", "ELINER", 131, -994),
        CreatePassengerDoor(247, 16, "Floor 64 passenger elevator, left door", "blin64", "ELINEL", -130, -994),
        CreatePassengerDoor(247, 17, "Floor 64 passenger elevator, right door", "blin64", "ELINER", 131, -994),
        CreatePassengerDoor(248, 7, "Floor 65 passenger elevator, left door", "blin65_1", "ELINEL", -130, -1009),
        CreatePassengerDoor(248, 8, "Floor 65 passenger elevator, right door", "blin65_1", "ELINER", 131, -1009),
        CreatePassengerDoor(250, 26, "Floor 66 passenger elevator, left door", "blin66_1", "ln0", -130, -984),
        CreatePassengerDoor(250, 27, "Floor 66 passenger elevator, right door", "blin66_1", "ln1", 131, -984),
        CreatePassengerDoor(264, 16, "Floor 69 passenger elevator, left door", "blin69_1", "elel", -133, -995),
        CreatePassengerDoor(264, 17, "Floor 69 passenger elevator, right door", "blin69_1", "eler", 129, -995)
    ];

    public static IReadOnlyList<FieldNavigationObjectDefinition> Create() =>
        Definitions;

    private static FieldNavigationObjectDefinition CreatePassengerDoor(
        int fieldId,
        int entityId,
        string label,
        string sourceFieldName,
        string sourceEntityName,
        int x,
        int y) =>
        new(
            fieldId,
            entityId,
            FieldNavigationObjectKind.Named,
            Label: label,
            SourceFieldName: sourceFieldName,
            SourceEntityName: sourceEntityName,
            TargetKind: FieldNavigationObjectTargetKind.Line,
            StaticX: x,
            StaticY: y,
            StaticZ: 0);
}
